name: Run Python Scripts Automatically in Pairs

on:
  schedule:
    # 每日台灣時間13:00 (相當於 UTC 時間05:00)
    - cron: '50 3 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2  # 一次最多執行兩個腳本
      matrix:
        script:
          - 'seoul_busi_flights.py'
          - 'seoul_eco_flights.py'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 使用最新版本檢出存儲庫

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests webdriver-manager

    - name: Run script
      run: |
        python ${{ matrix.script }}  # 動態運行矩陣中的 Python 腳本

    - name: Upload CSV as artifacts
      uses: actions/upload-artifact@v3  # 上傳 CSV 文件
      with:
        name: flight-data
        path: /*.csv  # 匹配所有生成的 CSV 文件
